### ISSUE TITLE
Error when running Server instructions

### ISSUE THREAD

**Issue by amitnovick** [fulcrologic/fulcro-todomvc#2]
Hi there!

I was trying to play with a Fulcro example today to get a better taste of what it's like, but stumbled upon an error, so I'm kinda bummed about that.

Perhaps there is something that I'm missing or maybe this is something that can be fixed only after thorough inspection? not sure.

```
╰─$ lein --version                                                            
Leiningen 2.9.1 on Java 1.8.0_192 OpenJDK 64-Bit Server VM
```

```
 $ lein repl                                                                 
19-05-08 23:02:54 MyPad WARN [fulcro.datomic.schema:227] - Caching migrations, set env var FULCRO_DATOMIC_CACHE_MIGRATIONS to 0 or false to disable.
[WARNING] No nREPL middleware descriptor in metadata of #'cemerick.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
nREPL server started on port 34309 on host 127.0.0.1 - nrepl://127.0.0.1:34309
ERROR: Unhandled REPL handler exception processing message {:id a8de99f8-4cfd-4831-a547-60587ee1957b, :op clone}
java.lang.NullPointerException
	at clojure.core$deref_future.invokeStatic(core.clj:2292)
	at clojure.core$deref.invokeStatic(core.clj:2312)
	at clojure.core$deref.invoke(core.clj:2298)
	at cemerick.piggieback$wrap_cljs_repl$fn__42242.invoke(piggieback.clj:289)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__28135.invoke(middleware.clj:22)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
	at nrepl.server$handle_STAR_.invoke(server.clj:15)
	at nrepl.server$handle$fn__41700.invoke(server.clj:27)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by awkay** [comment]
Try now...middleware went out of date and seems broken with newer lein

**Comment by amitnovick** [comment]
> Try now...middleware went out of date and seems broken with newer lein

Just tried this now and... It's humming along like a well-oiled machine!

This is a perfect learning material for me, thank you for promptly addressing this! awesome. :-)
